# Generated by Django 2.2 on 2020-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='alamat',
            field=models.CharField(default='', max_length=100),
        ),
    ]
