# Generated by Django 2.2 on 2020-10-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_auto_20201028_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='toko',
            name='telp',
            field=models.PositiveSmallIntegerField(default=0, max_length=15),
        ),
    ]
