# Generated by Django 2.2 on 2020-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_toko_telp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='telp',
            field=models.PositiveIntegerField(default=0, max_length=15),
        ),
    ]
