# Generated by Django 2.2 on 2020-10-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_auto_20201029_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='telp',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
