# Generated by Django 2.2 on 2020-10-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0005_auto_20201029_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='telp',
            field=models.CharField(default='', max_length=15),
        ),
    ]
